export const samplePosts = [
  {
    id: "morning-gallery",
    title: "朝の撮影ギャラリー Vol.1",
    description: "自然光で撮影した限定フォトセット。加入前のファンにも雰囲気が伝わる安全プレビュー付きです。",
    cover: "/themes/studio-pro.png",
    timeAgo: "2日前",
    isLocked: true,
    requiredTier: "Standard",
    badge: "new",
    media: [
      { id: "m1", url: "", type: "VIDEO", isSample: false, duration: 180 },
      { id: "m2", url: "", type: "IMAGE", isSample: false, duration: null },
    ],
  },
  {
    id: "room-tour",
    title: "限定ルームツアー動画",
    description: "ファン向けに公開する短尺動画のサンプル。Premiumプラン加入者だけが本編を閲覧できます。",
    cover: "/themes/neon-pro.png",
    timeAgo: "5日前",
    isLocked: true,
    requiredTier: "Premium",
    badge: "new",
    media: [
      { id: "m3", url: "", type: "VIDEO", isSample: false, duration: 754 },
    ],
  },
  {
    id: "single-sale-set",
    title: "単品販売フォトセット",
    description: "月額プランに入っていないファンにも販売できる単品コンテンツのサンプルです。",
    cover: "/themes/velvet-pro.png",
    timeAgo: "1週間前",
    isLocked: true,
    price: 1200,
    badge: "new",
    media: [
      { id: "m4", url: "", type: "IMAGE", isSample: false, duration: null },
      { id: "m5", url: "", type: "IMAGE", isSample: false, duration: null },
      { id: "m6", url: "", type: "IMAGE", isSample: false, duration: null },
    ],
  },
  {
    id: "behind-scenes",
    title: "撮影の裏側メモ",
    description: "本文投稿、画像、短い動画を組み合わせた更新例。制作過程をファンに届けられます。",
    cover: "/themes/creator-pro.png",
    timeAgo: "2週間前",
    isLocked: true,
    requiredTier: "Standard",
    media: [
      { id: "m7", url: "", type: "VIDEO", isSample: false, duration: 360 },
    ],
  },
  {
    id: "premium-archive",
    title: "Premiumアーカイブ 4月分",
    description: "過去投稿をまとめたアーカイブ販売の表示例。既存ファンにも新規ファンにも訴求できます。",
    cover: "/themes/zine-lite.png",
    timeAgo: "3週間前",
    isLocked: true,
    price: 2800,
    media: [
      { id: "m8", url: "", type: "VIDEO", isSample: false, duration: 420 },
      { id: "m9", url: "", type: "IMAGE", isSample: false, duration: null },
    ],
  },
  {
    id: "preview-safe",
    title: "SNS告知用プレビュー",
    description: "Xで告知しやすい安全なサムネイルと、サイト内の本編導線を分けた投稿例です。",
    cover: "/themes/pure-lite.png",
    timeAgo: "1か月前",
    isLocked: true,
    requiredTier: "Standard",
    media: [
      { id: "m10", url: "", type: "VIDEO", isSample: false, duration: 300 },
    ],
  },
];
